monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type:  rotating_file
                path:  '%kernel.logs_dir%/debug.log'
                level: debug
                max_files: 3
            error:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/error.log'
                level: error
                max_files: 3
            warning:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/warning.log'
                level: warning
                max_files: 3
            info: 
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/info.log'
                level: "info"
                max_files: 3
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type:  rotating_file
                path:  '%kernel.logs_dir%/debug.log'
                level: debug
                max_files: 3
            error:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/error.log'
                level: error
                max_files: 3
            warning:
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/warning.log'
                level: warning
                max_files: 3
            info: 
                type: rotating_file
                path: '%kernel.logs_dir%/%kernel.environment%/info.log'
                level: "info"
                max_files: 3